parameters:
    #GMail
    #mailer_transport: gmail
    #mailer_user: saas@docxpresso.com
    #mailer_password: 6102saasnononsense
    #SendGrid
    mailer_transport: smtp
    mailer_user: cesar.martin@nodalblock.es
    mailer_host: smtp.strato.com
    mailer_port: 465
    mailer_encryption: ~
    mailer_username: cesar.martin@nodalblock.com
    mailer_password: BCHCE/(BKH22