parameters:
    #GMail
    #mailer_transport: gmail
    #mailer_user: saas@docxpresso.com
    #mailer_password: 6102saasnononsense
    #SendGrid
    mailer_transport: smtp
    mailer_host: smtp.strato.com
    mailer_user: soporte@nodalblock.com
    mailer_password: '4a@exE@7=+jc?5qWVz2C'
    mailer_encryption: ssl
    mailer_username: soporte@nodalblock.com