parameters:
    #GMail
    #mailer_transport: gmail
    #mailer_user: saas@docxpresso.com
    #mailer_password: 6102saasnononsense
    #SendGrid
    mailer_transport: smtp
    mailer_host: smtp.mailtrap.io
    mailer_user: c7b726ae6387d9
    mailer_password: 58e1269fe25124
    mailer_encryption: null
    mailer_username: test@gsk.com
