nononsense_group:
    resource: "@NononsenseGroupBundle/Resources/config/routing.yml"
    prefix:   /groups

nononsense_user:
    resource: "@NononsenseUserBundle/Resources/config/routing.yml"
    prefix:   /users
    
nononsense_notifications:
    resource: "@NononsenseNotificationsBundle/Resources/config/routing.yml"
    prefix:   /messages
    
nononsense_home:
    resource: "@NononsenseHomeBundle/Resources/config/routing.yml"
    prefix:   /