nononsense_user_login:
    path:     /login
    defaults: { _controller: NononsenseUserBundle:Login:login }
    
nononsense_user_check:
    path:     /check_user
    
nononsense_user_logout:
    path:     /logout
    
nononsense_user_login_init:
    path:     /login_init
    defaults: { _controller: NononsenseUserBundle:Login:userLoginInit }
    
nononsense_user_recover_password:
    path:     /recover_password/{error}
    defaults: { _controller: NononsenseUserBundle:Login:recoverPassword, error: 0 }
    
# nononsense_user_request_account:
#     path:     /request_account
#     defaults: { _controller: NononsenseUserBundle:Login:requestAccount }
    
nononsense_user_keep_alive:
    path:     /keep-alive
    defaults: { _controller: NononsenseUserBundle:Users:keepAlive }
    
nononsense_user_profile:
    path:     /profile/{id}
    defaults: { _controller: NononsenseUserBundle:Users:show }
    requirements:
        id: ".+"
        
nononsense_user_profile_slash:
    path:     /profile
    defaults: { _controller: NononsenseUserBundle:Users:show}
    requirements:
        id: ".+"
    
nononsense_user_create:
    path:     /create
    defaults: { _controller: NononsenseUserBundle:Users:create }
    
nononsense_user_edit:
    path:     /edit/{id}
    defaults: { _controller: NononsenseUserBundle:Users:edit}
    requirements:
        id: ".+"
    
nononsense_user_edit_image:
    path:     /editImage/{id}
    defaults: { _controller: NononsenseUserBundle:Users:editImage}
    requirements:
        id: ".+"
        
nononsense_user_modify_password:
    path:     /modifyPassword/{id}
    defaults: { _controller: NononsenseUserBundle:Users:resetPassword}
    requirements:
        id: ".+"
        
nononsense_user_delete:
    path:     /delete/{id}
    defaults: { _controller: NononsenseUserBundle:Users:delete, id: 1}
    requirements:
        id: ".+"
        
nononsense_users_access_token:
    path:     /accessByToken
    defaults: { _controller: NononsenseUserBundle:Login:accessByToken}
    
nononsense_users_load_csv:
    path:     /load_users
    defaults: { _controller: NononsenseUserBundle:Users:loadUsers}

# New users index (nononsense_users_report by nononsense_users_homepage)
# nononsense_users_report:
#     path:     /report
#     defaults: { _controller: NononsenseUserBundle:Users:report}

nononsense_user_crate_requests:
    path:     /apply
    defaults: { _controller: NononsenseUserBundle:AccountRequest:create}
    methods:  [GET, POST]

nononsense_user_check_requests:
    path:     /requests
    defaults: { _controller: NononsenseUserBundle:AccountRequest:index}
    methods:  [GET]

nononsense_user_ajax_update_requests:
    path:     /requests/ajax
    defaults: { _controller: NononsenseUserBundle:AccountRequest:ajaxUpdate}
    methods:  [GET, PUT]

nononsense_user_ajax_get_mudid:
    path:     /requests/check_user
    defaults: { _controller: NononsenseUserBundle:AccountRequest:getMudId}
    methods:  [GET]

nononsense_user_update_requests:
    path:     /requests/{id}
    defaults: { _controller: NononsenseUserBundle:AccountRequest:update}
    requirements:
        id: '\d+'
    methods:  [GET, PUT]
    
nononsense_users_ldap:
    path:     /ldap
    defaults: { _controller: NononsenseUserBundle:Login:ldapComponent}

nononsense_users_log:
    path:     /log
    defaults: { _controller: NononsenseUserBundle:Access:log}

nononsense_users_homepage:
    # path:     /{page}/{query}
    # defaults: { _controller: NononsenseUserBundle:Users:index, page: 1, query: 'q'} Old users index
    path:     /{query}
    defaults: { _controller: NononsenseUserBundle:Users:report, query: 'q'}
        
# nononsense_users_homepage_slash:
#     path:     /
#     defaults: { _controller: NononsenseUserBundle:Users:index, page: 1, query: 'q'}
    
