services:
  utilities:
    class: Nononsense\HomeBundle\Utils\Utilities
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@logger"
      - "@session"
      - "@service_container"
      - "@templating"